#+TITLE: go-imenu.el
[[http://www.gnu.org/licenses/gpl-3.0.html][file:https://img.shields.io/badge/license-GPL_v3-green.svg]]
[[https://melpa.org/#/go-imenu][file:https://melpa.org/packages/go-imenu-badge.svg]]
[[https://stable.melpa.org/#/go-imenu][file:https://stable.melpa.org/packages/go-imenu-badge.svg]]

* Introduction
  :PROPERTIES:
  :ID:       DE46A955-F481-47FC-BA02-77DEAB49BA63
  :END:
  
  Imenu for go language!
  
  go-mode.el use elisp, base [[https://github.com/dominikh/go-mode.el/blob/120fb911f1d8038f828da85eed8aaad977dabd8c/go-mode.el#L990][regex]].
  
  go-imenu.el use go, base  go's package([[https://github.com/lukehoban/go-outline/blob/e785568742524aa488d7332e7619dba87b2a8b9d/main.go#L8][ast/parse/token/format]]).
  
  #+BEGIN_EXAMPLE
  If you want to know more details, please click on the link above.
  I think go's package is simpler, faster, and more accurate than elisp's regular expression.
  #+END_EXAMPLE

* Dependency
  :PROPERTIES:
  :ID:       DE26A168-2425-4626-A658-BBE5FFE58680
  :END:

  #+BEGIN_SRC shell
    go get -u github.com/lukehoban/go-outline
  #+END_SRC

* Installation
  :PROPERTIES:
  :ID:       308CCDB0-EFBD-4E67-982C-D3B4458E8B91
  :END:

  Available on all major ~package.el~ community maintained repos -
  [[https://stable.melpa.org/#/][MELPA Stable]] and [[https://melpa.org/#/][MELPA]] repos.

  MELPA Stable is recommended as it has the latest stable version.
  MELPA has a development snapshot for users who don't mind breakage but
  don't want to run from a git checkout.

  You can install ~go-imenu~ using the following command:

  ~M-x package-install [RET] go-imenu [RET]~

  or if you'd rather keep it in your dotfiles:

  #+BEGIN_SRC elisp
  (unless (package-installed-p 'go-imenu)
    (package-refresh-contents)
    (package-install 'go-imenu))
  #+END_SRC

  If the installation doesn't work try refreshing the package list:

  ~M-x package-refresh-contents~

* Setup
  :PROPERTIES:
  :ID:       98BB72C0-8873-471D-963C-06D7206DA178
  :END:

  Call go-imenu-setup function at go-mode-hook
  #+BEGIN_SRC elisp
  (require 'go-imenu) ;; Don't need to require, if you install by package.el
  (add-hook 'go-mode-hook 'go-imenu-setup)
  #+END_SRC
